# Block scanners & bots
map $request_uri $block_uri {
    default 0;
    ~*\.(php|asp|aspx|jsp|cgi|env|bak|sql|swp)$ 1;
    ~*/wp-(admin|login|content|includes) 1;
    ~*/xmlrpc 1;
    ~*/\.git 1;
    ~*/phpmyadmin 1;
    ~*/\.env 1;
}
